(defmacro extend(name params If test &body body)
  (let ((args (uniq)))
    `(let ((orig (symbol-function ',name)))
       (setf (symbol-function ',name)
             (lambda(&rest ,args)
               (if (apply (lambda ,params ,test) ,args)
                 (apply (lambda ,params ,@body) ,args)
                 (apply orig ,args)))))))
