#!/usr/bin/env zsh

# ldb usually pops up when wart has infinite recursion and blows the stack
export COMMON_ARGS="--disable-ldb --noinform --userinit sbclrc"

if [ $# -eq 0 ]
then
  rlwrap sbcl `echo $COMMON_ARGS` --load boot
elif [[ $1 == 'test' ]]
then
  rlwrap sbcl `echo $COMMON_ARGS` --load test --eval '(quit)'
else
  (
    for i in $*
    do
      echo "(load \"$i\")"
    done
    echo "(quit)"
  ) > .wartbatch
  rlwrap sbcl `echo $COMMON_ARGS` --eval '(setf batch-mode* t)' --load boot --load .wartbatch
  rm .wartbatch
fi
