#!/bin/sh

# show commands if run
# show nothing if not run
# exit if commands failed
make |grep -v "is up to date" >&2
[ ${PIPESTATUS[0]} -eq 0 ] || exit 1

if command which rlwrap >/dev/null
then
  rlwrap -C wart ./wart_bin $*
else
  ./wart_bin $*
fi
