#!/bin/sh

# if running tests, assume we're making constant changes
# otherwise turn on optimizations
if [ "$1" == "test" ]
then
  # silent if up to date
  make -q || make >&2 || exit 1
else
  make -q || make opt >&2 || exit 1
fi

if command which rlwrap >/dev/null
then
  rlwrap -C wart ./wart_bin $*
else
  ./wart_bin $*
fi
